### ISSUE TITLE
Please use semantic versioning

### ISSUE THREAD

**Issue by yas4891** [cortiz/prawn-rails#20]
Hi, 

your latest update from `0.1.0` to `0.1.1` contained a breaking change. 
Please don't do that and please adhere to semantic versioning (http://semver.org/).

**Comment by cortiz** [comment]
I know , I'm sorry for that , I was a mistake on my release script , I
won't happened again

2015-02-23 16:50 GMT-06:00 yas4891 <notifications@github.com>:

**Comment by yas4891** [comment]
@cortiz Hey Carlos. 
no worries. Thanks for building the gem!

Cheers,
Christoph
