### ISSUE TITLE
Couldn't change the filename using @filename

### ISSUE THREAD

**Issue by ferryphang** [cortiz/prawn-rails#21]
Hi i have some issue with prawn-rails when i want to change my filename when prawn generate my pdf..
so i have routes 

```
def pdf
  @file_name = "example.pdf"
end
```

and i have `pdf.pdf.prawn` but when it generate my pdf file name stay the same
http://localhost:3000/templates/pdf.pdf

am i do anything wrong here

**Comment by Pepan** [comment]
Same here.

There was options like :filename=>'Hello.pdf', :force_download=>true,  in prawn_document method in the past. Where it disappeared?

https://github.com/Whoops/prawn-rails#force-saving

**Comment by chris-gooley** [comment]
This doesn't appear to work in IE11.
The following code changes the filename in Chrome but does not work in IE11

```ruby
format.pdf do
  @filename = "NewFileName.pdf"
  render 'report'
end
```

**Comment by westonganger** [comment]
@chris-gooley did you ever figure out how to get it working in IE11?

**Comment by chris-gooley** [comment]
I rested it and it appears to be working. I can't exactly remember what I did to fix it but it could potentially have been a bug elsewhere. Sorry thats not much help, but it was over 6 months ago :P

**Comment by westonganger** [comment]
Did you test Edge or Internet Explorer? 

Maybe my organization is running an IE compatibility mode or something.
