### ISSUE TITLE
ActionController::UnknownFormat

### ISSUE THREAD

**Issue by bhushangahire** [cortiz/prawn-rails#22]
Installed Gem and created pdf.prawn view. When I am accessing url with .pdf. Its giving me ActionController::UnknownFormat Do I need to register the Mime type again ?

**Comment by westonganger** [comment]
Do you have a `respond_to` statement in your controller? If so it has to allow `:pdf`.

**Comment by solipet** [comment]
@bhushangahire did you try something like this?:
```
# config/mime_types.rb
Mime::Type.register "application/pdf", :pdf
```

**Comment by westonganger** [comment]
This gem already registers that mime type. So you should not have to register it yourself.

**Comment by solipet** [comment]
Ah, cool -- thanks!

**Comment by bhushangahire** [comment]
Not sure what I did. But I guess we can close this.

**Comment by costa** [comment]
You have to restart the server upon serving your first prawn... for some reason.

**Comment by westonganger** [comment]
@costa this because it registers a new controller renderer for pdf.prawn files. You have to restart your server to get this installed. You should always be restarting your server after installing new gems amongst many other tasks.
