### ISSUE TITLE
Possible missing step or error in README?

### ISSUE THREAD

**Issue by dfaulken** [cortiz/prawn-rails#26]
From [this StackOverflow question](https://stackoverflow.com/questions/44187156/undefined-method-pdf-with-prawn-rails), I've followed the instructions in the README (unless I missed something small) but I have an `undefined local variable or method 'pdf' for #<#<Class:0x005618ff5021e8>:0x005618ff97b968>` in the prawn file, written as in the example.

Feel free to check out my current source [here](https://github.com/umts/incidents/tree/pdf) with the relevant commit [here](https://github.com/umts/incidents/commit/ececee8839c41f92aa3217e5d13b656d47ac9ffa).

Thanks!

**Comment by dfaulken** [comment]
Someone [proposed](https://stackoverflow.com/questions/44187156/undefined-method-pdf-with-prawn-rails/44187304#answer-44187304) that the example should read

```ruby
prawn_document do |pdf|
  pdf.text "Some text"
end
```

But that gives me `undefined method '-' for nil:NilClass`.

**Comment by westonganger** [comment]
I have now updated the readme so that the examples are correct.

As for the error you are getting now I am not sure why this is happening. Are you certain you are using `prawn-rails` and NOT `prawn_rails` in your Gemfile?

**Comment by dfaulken** [comment]
Great! Yes, [I do have a dash and not an underscore](https://github.com/umts/incidents/commit/ececee8839c41f92aa3217e5d13b656d47ac9ffa#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R10).

**Comment by westonganger** [comment]
You are probably getting this error because in your config you have chosen to `skip_page_creation = true` which means you must call` pdf.start_new_page` before you can write anything to the pdf (ie. `pdf.text`).

The default is `skip_page_creation = false` which always creates the first page automatically for you.

**Comment by dfaulken** [comment]
Yep, that's it. My mistake. Thanks!
