### ISSUE TITLE
Prawn::Emoji Support?

### ISSUE THREAD

**Issue by CodingAnarchy** [cortiz/prawn-rails#28]
I was attempting to integrate [`prawn-emoji`](https://github.com/hidakatsuya/prawn-emoji) support into my app so we can display emojis inside the PDFs, but it doesn't seem possible to use this with the `prawn-rails` configuration. Is there any way this can be changed so these integrate automatically?

**Comment by westonganger** [comment]
This snippet was taken from the `prawn-emoji` readme.

> In order to run the following code, you need to place both DejaVuSans.ttf and ipag.ttf in the same directory as the script file.

Does `prawn-emoji` even work with Rails?

**Comment by CodingAnarchy** [comment]
The code in the `prawn-emoji` readme requires the `.ttf` files in the same directory due to the way it handles setting the font in the example script.  It works if you move the font files elsewhere and provide a link to that font file.  That functionality is just `prawn` setting the font to be used.

It's only in the case of using `prawn-rails` to set up the template as a `*.pdf.prawn` file that I'm having the problem where the `prawn-emoji` functionality won't integrate.

**Comment by westonganger** [comment]
In a Rails app, same directory means where? as the view file?

As for requiring, here is where the plugin gems are required:
https://github.com/cortiz/prawn-rails/blob/448c345a338db4373149925a0be95f13daa24542/lib/prawn-rails/document.rb#L1-L2

I don't want this to be a dependency in the gemspec, I guess I could add something along the lines of the following? 

```ruby
if Gem::Specification::find_all_by_name('prawn-emoji').any?
  require 'prawn-emoji'
end
```

Would this even work with the ttf same directory constraint? Also I suppose I would have to do this for every prawn integration library out there which is definitely not ideal.

**Comment by CodingAnarchy** [comment]
> Would this even work with the ttf same directory constraint?

This constraint is simply for `prawn` to find the file when given `pdf.font 'DejaVuSans.ttf'`.  It only applies to the example as written.

> I suppose I would have to do this for every prawn integration library out there which is definitely not ideal.

I would suspect there would be a way to do that for every `prawn-` library.  Something like the following pseudocode:

```ruby
list_of_installed_gems_by_prefix('prawn-').each do |gem_name|
  require gem_name.gsub('-', '/')
end
```

I'm not familiar enough with `rubygems` to know how to get that list of gem names, though.

**Comment by westonganger** [comment]
Ah okay I understand. Good suggestion for the loop, could be slightly surprising but we can burn that bridge once someone has a problem with it. Think you could create a PR for this?

**Comment by CodingAnarchy** [comment]
Sure, I can work on trying to come up with a PR for it.  Just have to delve into `rubygems` a bit. 👍

**Comment by westonganger** [comment]
v1.1.0 released which includes this feature.
