### ISSUE TITLE
Add an option to control Content-Disposition

### ISSUE THREAD

**Issue by TylerRick** [cortiz/prawn-rails#33]
It [looks](https://github.com/cortiz/prawn-rails/blob/master/lib/prawn-rails/renderer.rb) like there's a way to control the filename (by setting `@filename`), but the Content-Disposition is hard-coded to be "inline":
```
          controller.response.headers['Content-Disposition'] = "inline; filename=\\\"\#{@filename}\\\""
```

Could we add an option for controlling whether Content-Disposition is inline or attachment like [prawnto has](https://github.com/smecsia/prawnto/blob/master/lib/prawnto/template_handler/compile_support.rb#L58)?
```
      def set_disposition
        inline = options[:inline] ? 'inline' : 'attachment'
        filename = options[:filename] ? "filename=\"#{options[:filename]}\"" : nil
        @controller.headers["Content-Disposition"] = [inline,filename].compact.join(';')
      end
```
Maybe we need an options hash?

**Comment by westonganger** [comment]
@TylerRick any chance to take a stab at this?

**Comment by waghanza** [comment]
@cortiz I can make a `PR` if you want

**Comment by waghanza** [comment]
ok :stuck_out_tongue_winking_eye:, I'm on it

**Comment by ATMartin** [comment]
@waghanza Just checking in: are you still working on this feature? I'd like to take over if not. We got burned by this after a recent upgrade.

**Comment by westonganger** [comment]
@ATMartin go for it

**Comment by waghanza** [comment]
@ATMartin not working on this anymore, glad you take over
