### ISSUE TITLE
Load a custom ttf font

### ISSUE THREAD

**Issue by waghanza** [cortiz/prawn-rails#35]
Hi @westonganger,

Is it possible to load a custom **TTF** font in rails initializer ?

I mean that `prawn` use **AFM** font  `type` by default and I want to use **TTF** one (for `utf-8` support).

I have access to ttf file, I load them when generating document
~~~ruby
pdf.font_families.update("Helvetica": {
    normal: Rails.root.join("app/assets/fonts/Helvetica.ttf"),
    italic: Rails.root.join("app/assets/fonts/Helvetica-Oblique.ttf"),
    bold: Rails.root.join("app/assets/fonts/app/assets/fonts/Helvetica-Bold.ttf"),
    bold_italic: Rails.root.join("app/assets/fonts/Helvetica-BoldOblique.ttf")
    })
~~~

Regards,

**Comment by pointlessone** [comment]
This code only updates a hash. It doesn't load fonts or do anything else. This operation is not expensive and won't save you much CPU time to move it into initializer. Do it wherever you instantiate a document.

**Comment by waghanza** [comment]
In fact I want to load custom fonts globally

**Comment by pointlessone** [comment]
Make it a constant if you want to keep only one instance of the list:
```ruby
MY_FONTS = {
  "Helvetica": {
    normal: Rails.root.join("app/assets/fonts/Helvetica.ttf"),
    italic: Rails.root.join("app/assets/fonts/Helvetica-Oblique.ttf"),
    bold: Rails.root.join("app/assets/fonts/app/assets/fonts/Helvetica-Bold.ttf"),
    bold_italic: Rails.root.join("app/assets/fonts/Helvetica-BoldOblique.ttf"),
  }
}
```

Elsewhere:
```ruby
pdf.font_families.update(MY_FONTS)
```

**Comment by waghanza** [comment]
I think  I mis-express myself

When I execute `rspec`, `prawn| is loaded with some **afm** fonts, and I need to load **ttf** fonts 

I have an error when executing my `spec`
~~~ruby
/usr/share/gems/gems/prawn-2.2.2/lib/prawn/font/afm.rb:105:in `normalize_encoding'
~~~

**Comment by pointlessone** [comment]
AFM is not a font. It's a font metric. It basically contains only character sizes and advances (how far cursor should move after a specific character). Those are only present for so called PDF built-in fonts. Those are 14 actual Adobe fonts that should be distributed with any PDF renderer (software that reads PDF files and produces some sort of image, either for displaying on a screen, or printing, or saving to a file, etc.). The AFM files used in Prawn for laying out the text but no actual fonts ever included in the PDFs. That is when you us any of those default fonts. The code is not used when you use a TTF font.

**Comment by waghanza** [comment]
As I understand, **ttf** fonts **SHOULD** be included on the software which read pdf ?

**Comment by pointlessone** [comment]
These 14 default fonts — yes. Any other font has to be embedded into PDF file. Thats's what happens when you use your own TTF fonts with Prawn.

**Comment by waghanza** [comment]
Thanks for explaination :stuck_out_tongue: 

It appears that my problem was about a `nil` that was sent in https://github.com/prawnpdf/prawn/blob/master/lib/prawn/font/afm.rb#L108 (because of a **nilable** field in database)

**Comment by pointlessone** [comment]
Oh well. I may consider tightening up Prawn's public API to not allow that but as of right now you should make sure you're providing proper data to Prawn.

**Comment by waghanza** [comment]
I've found a way to do this :stuck_out_tongue: but up to you to choose between allowing `nil` or **documenting this**

I can also provide any `PR`, if you want :stuck_out_tongue_winking_eye:
