### ISSUE TITLE
Rails 6: Deprecation Warning: Single arity template handlers are deprecated.

### ISSUE THREAD

**Issue by alaarab** [cortiz/prawn-rails#38]
When running rails, on Rails 6.0.0rc1, I get the following output.

```
DEPRECATION WARNING: Single arity template handlers are deprecated. Template handlers must now accept two parameters, the view object and the source for the view object.
Change:

PrawnRails::Renderer.call(template)
To:
PrawnRails::Renderer.call(template, source)
```

I thought this might be related to: https://github.com/cortiz/prawn-rails/issues/37

However, I added the latest version of Temple (even though I had no reference to it in my app), and am still receiving the deprecation warning. It looks like an issue from PrawnRails itself, based on the issue above. 

I believe this file is the culprit: https://github.com/cortiz/prawn-rails/blob/master/lib/prawn-rails/renderer.rb

When I forked this repo, and changed line 7 of Renderer.rb and modified

    def self.call(template)
to
    def self.call(template, source)

I was no longer receiving the Deprecation Warning.

**Comment by westonganger** [comment]
Fixed by #39
