### ISSUE TITLE
DEPRECATION WARNING: Rendering actions with '.' in the name is deprecated

### ISSUE THREAD

**Issue by A5308Y** [cortiz/prawn-rails#43]
Hello there and thanks for prawn-rails!

We're seeing a deprecation warning since a recent rails upgrade:
```
DEPRECATION WARNING: Rendering actions with '.' in the name is deprecated: .../show.pdf.prawn
```
We're rendering a file the way suggested in `https://github.com/cortiz/prawn-rails/issues/32`, but I assume this is an issue with all templates that follow the file naming convention from [your docs](https://github.com/cortiz/prawn-rails#usage).

Is this something you're aware of? Are you working on a fix or do you have a suggestion on how to fix the issue on our side?

Thanks in advance and all the best!

**Comment by westonganger** [comment]
Can you show me the call to the render action from your controller code?

**Comment by A5308Y** [comment]
Hi @westonganger, thanks for the quick reply. It looks like this:

```ruby
Admin::ContractsController.render(
  template: "admin/contracts/show.pdf.prawn",
  assigns: {
    decorated_pdf_contract: DecoratedPdfContract.new(@contract)
  }
)
```

**Comment by westonganger** [comment]
So you are trying to render to a string? We discussed this in https://github.com/cortiz/prawn-rails/issues/32

Maybe try one of the following (untested):

```ruby
render_to_string(
  "admin/contracts/show", 
  formats: [:pdf],
  assigns: {
    decorated_pdf_contract: DecoratedPdfContract.new(@contract)
  }
)

### OR

Admin::ContractsController.render(
  template: "admin/contracts/show",
  formats: [:pdf],
  assigns: {
    decorated_pdf_contract: DecoratedPdfContract.new(@contract)
  }
)
```

**Comment by A5308Y** [comment]
Oh man. This is embarrassing. I tried `format` (without the "s") and gave up when it didn't work...

```ruby
template: "admin/contracts/show",
formats: [:pdf],
```

Works perfectly.

Thanks again for the quick responses @westonganger!

**Comment by westonganger** [comment]
:D
