### ISSUE TITLE
PrawnRails initializer doesn't get loaded

### ISSUE THREAD

**Issue by atstockland** [cortiz/prawn-rails#46]
I recently moved to this gem instead of separately using prawn and prawn-table.  The initializer, I thought, would be handy.

In each of my PDF's I would call something like:

     super(top_margin: 30, right_margin: 50, page_size: 'LETTER', page_layout: :portrait)

I removed that content from each file and placed those setting in an initializer---as recommended in your readme.

PrawnRails.config do |config|
  config.page_layout = :portrait
  config.page_size   = 'LETTER'
  config.skip_page_creation = false
  config.top_margin = 30
  config.left_margin = 50
  config.compress = true

  config.info = {
    Title: 'xxxxx PDF',
    Author: 'xxxxxxx',
    Subject: 'xxxxx PDF',
    Keywords: 'xxxxxx',
    Creator: 'xxxxx',
    Producer: 'Prawn',
    CreationDate: Time.now
  }
end

If I load the PDF using super to set the options, the page is created as expected.  If I remove super, and and expect the options to be set in the initializer, the PDF fails to load.  The first error is "undefined method `page' for nil:NilClass".  It seems the document doesn't understand the page structure without using super to define the options.

**Comment by westonganger** [comment]
Are you using `prawn_document(options) do |pdf|` in your view files as described in the readme?

**Comment by atstockland** [comment]
No I wasn't.  My PDFs inherit from "< Prawn::Document" so I don't call "pdf.text"---I just call "text".  To use this gem would I place "prawn_document(options) do |pdf|" inside my PdfReport < Prawn::Document class?

**Comment by westonganger** [comment]
Show an example file / piece of code

**Comment by atstockland** [comment]
# frozen_string_literal: true
class SamplePdf < Prawn::Document

  def initialize(user_id, options = {})
    super top_margin: 30, left_margin: 50, page_size: 'LETTER', page_layout: :portrait
    define_grid(columns: 2, rows: 16, gutter: 10)

    grid([1,0],[1,1]).bounding_box do
        text "some text"
    end

end

**Comment by westonganger** [comment]
Should probably work if you change your class name from `Prawn::Document` to `PrawnRails::Document` then you shouldnt use super anymore.

**Comment by westonganger** [comment]
Ok I've confirmed this all works.

I've written some missing tests for the config feature and I also added tests which use the alternate usage you have described.

I've also added documentation to the readme for this style of usage: https://github.com/cortiz/prawn-rails#without-using-the-prawn_document-helper

Closing.
