### ISSUE TITLE
Have you ever been able to make it run on Heroku?

### ISSUE THREAD

**Issue by carlesjove** [cortiz/prawn-rails#5]
Hello Carlos. First of all, let me apologize, for I know this is not the place to ask this. But I haven't been able to find your email or a private way to contact you.

I have used this gem successfully in a Rails 4 app, locally. When deploying to Heroku, the PDF can't be accessed and the app throws an error. I might be doing something wrong, I know, so I'd just like to know if you have successfully ran this gem on Heroku.

(Note: I can correctly show PDFs if I just use the Prawn gem, without prawn-rails)

**Comment by westonganger** [comment]
This project works on Heroku. Closing this issue as its old now.
