### ISSUE TITLE
Can't implement config in initializer

### ISSUE THREAD

**Issue by irashkin** [cortiz/prawn-rails#6]
Hi, I followed your instructions for setting config in /initializers/prawn-rails.rb, but I keep getting the error unidentified method `config' for PrawnRails::Module. I guess my other option is to revert to Issue #3's commit and hard code landscape into the instantiation, but I sure like the idea of the config better. Any advice on making this work?

**Comment by marnen** [comment]
@jfeust Same problem with 0.1.0; initializers just seem to be ignored. Gonna try latest version from GitHub (261ed59ca55420a590811c31eadd9606d4c067ae).

**Comment by marnen** [comment]
OK, that did the trick (once I introduced the `prawn_document` wrapper, which wasn't supported in 0.1.0). @cortiz Can we have a release since the API apparently changed significantly>

**Comment by cortiz** [comment]
@marnen  Should be up as 0.1.1

**Comment by marnen** [comment]
Thanks! But since this is a breaking API change, should it have been 0.2.0? Anyway, I'll try the new gem -- I appreciate the quick response!
